### Make payment
POST http://localhost:8080/payments HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "correlationId": "4a7901b8-7d26-4d9d-aa19-4dc1c7cf60b3",
    "amount": "19.90"
}



### Audit
GET /payments-summary?from=2020-07-10T12:34:56.000Z&to=2020-07-10T12:35:56.000Z HTTP/1.1
Host: localhost:8080
Content-Type: application/json